name: Build APK

on:
  push:
    branches:
      - main  # Trigger on push to main branch (or any branch you want)

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner (can also use macOS or Windows)
    
    steps:
      # Check out the code from GitHub
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up JDK (needed for Android builds)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Install required dependencies (for example, Android SDK)
      - name: Install Android dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip commandlinetools-linux-6858069_latest.zip -d $HOME/android-sdk
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

      # Build the APK using Gradle
      - name: Build APK
        run: |
          ./gradlew assembleDebug  # Use assembleRelease for release APK

      # Upload the APK as an artifact (optional)
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
